@php($placementLabels = ['home_featured' => 'Accueil premium', 'catalog_top' => 'Haut du catalogue', 'category_boost' => 'Catégorie ciblée'])
<x-dashboards.sap-shell title="Forfaits sponsoring" subtitle="Le SAP fixe les prix et la durée. Exemple : 1 jour à 500 XOF." active="sponsoring-plans" :owners-count="$ownersCount" :clients-count="$clientsCount" :published-venues-count="$publishedVenuesCount" :pending-access-requests-count="$pendingAccessRequestsCount" :pending-sponsorships-count="$pendingSponsorshipsCount" :gross-payments-amount="$grossPaymentsAmount" :active-bookings-count="$activeBookingsCount">
    <div class="grid gap-6 xl:grid-cols-[400px_1fr]">
        <form method="POST" action="{{ route('sap.sponsorship-plans.store') }}" class="rounded-[28px] bg-white p-5 shadow-xl shadow-[#173e7a]/8 ring-1 ring-[#dce6f7]">
            @csrf
            <h2 class="text-xl font-extrabold text-[#07152f]">Nouveau forfait</h2>
            <div class="mt-5 space-y-3">
                <input name="name" required placeholder="Ex. Découverte 1 jour" class="h-12 w-full rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold">
                <select name="placement" class="h-12 w-full rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold">@foreach($placementLabels as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select>
                <div class="grid grid-cols-2 gap-3"><input name="price" type="number" min="1" required placeholder="Montant XOF" class="h-12 rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold"><input name="duration_days" type="number" min="1" max="365" required placeholder="Durée jours" class="h-12 rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold"></div>
                <textarea name="description" rows="3" placeholder="Description commerciale" class="w-full rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 py-3 text-sm font-bold"></textarea>
                <textarea name="features" rows="4" placeholder="Avantages, un par ligne" class="w-full rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 py-3 text-sm font-bold"></textarea>
                <button class="h-12 w-full rounded-2xl bg-[#2f6bff] text-sm font-extrabold text-white">Créer le forfait</button>
            </div>
        </form>
        <section class="rounded-[28px] bg-white p-5 shadow-xl shadow-[#173e7a]/8 ring-1 ring-[#dce6f7]">
            <div class="overflow-x-auto rounded-2xl border border-[#edf2fb]"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-[#f7faff] text-xs font-extrabold uppercase text-[#7d8aa7]"><tr><th class="px-4 py-3">Forfait</th><th class="px-4 py-3">Placement</th><th class="px-4 py-3">Prix</th><th class="px-4 py-3">Durée</th><th class="px-4 py-3">Statut</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-[#edf2fb]">@forelse($plans as $plan)<tr><td class="px-4 py-4"><p class="font-extrabold text-[#07152f]">{{ $plan->name }}</p><p class="text-xs font-bold text-[#64708a]">{{ $plan->description }}</p></td><td class="px-4 py-4 font-bold text-[#64708a]">{{ $placementLabels[$plan->placement] ?? $plan->placement }}</td><td class="px-4 py-4 font-extrabold">{{ number_format($plan->price, 0, ',', ' ') }} {{ $plan->currency }}</td><td class="px-4 py-4 font-bold">{{ $plan->duration_days }} jour{{ $plan->duration_days > 1 ? 's' : '' }}</td><td class="px-4 py-4">{{ $plan->is_active ? 'Actif' : 'Inactif' }}</td><td class="px-4 py-4 text-right"><x-dashboards.action-menu><form method="POST" action="{{ route('sap.sponsorship-plans.toggle', $plan) }}">@csrf<button class="w-full rounded-xl px-3 py-2 text-left {{ $plan->is_active ? 'text-[#b42318] hover:bg-[#fff6f6]' : 'text-[#2f6bff] hover:bg-[#f2f7ff]' }}">{{ $plan->is_active ? 'Désactiver ce forfait' : 'Réactiver ce forfait' }}</button></form></x-dashboards.action-menu></td></tr>@empty<tr><td colspan="6" class="px-4 py-10 text-center font-semibold text-[#64708a]">Aucun forfait sponsoring.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $plans->links() }}</div>
        </section>
    </div>
</x-dashboards.sap-shell>
