<x-dashboards.sap-shell title="Forfaits abonnement" subtitle="Définissez les offres mensuelles ou annuelles proposées aux PEE." active="subscriptions" :owners-count="$ownersCount" :clients-count="$clientsCount" :published-venues-count="$publishedVenuesCount" :pending-access-requests-count="$pendingAccessRequestsCount" :pending-sponsorships-count="$pendingSponsorshipsCount" :gross-payments-amount="$grossPaymentsAmount" :active-bookings-count="$activeBookingsCount">
    <div class="grid gap-6 xl:grid-cols-[400px_1fr]">
        <form method="POST" action="{{ route('sap.subscription-plans.store') }}" class="rounded-[28px] bg-white p-5 shadow-xl shadow-[#173e7a]/8 ring-1 ring-[#dce6f7]">
            @csrf
            <h2 class="text-xl font-extrabold text-[#07152f]">Nouvelle formule</h2>
            <div class="mt-5 space-y-3">
                <input name="name" required placeholder="Nom du forfait" class="h-12 w-full rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold">
                <div class="grid grid-cols-2 gap-3"><input name="price" type="number" min="0" required placeholder="Prix XOF" class="h-12 rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold"><select name="billing_period" class="h-12 rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold"><option value="monthly">Mensuel</option><option value="yearly">Annuel</option></select></div>
                <div class="grid grid-cols-2 gap-3"><input name="active_venues_limit" type="number" min="1" placeholder="Limite espaces" class="h-12 rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold"><input name="reduced_commission_rate" type="number" step="0.01" min="0" max="100" placeholder="Commission réduite %" class="h-12 rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold"></div>
                <input name="visibility_boost_level" type="number" min="0" max="10" value="0" placeholder="Niveau visibilité" class="h-12 w-full rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 text-sm font-bold">
                <textarea name="features" rows="4" placeholder="Avantages, un par ligne" class="w-full rounded-2xl border border-[#dce6f7] bg-[#f8fbff] px-4 py-3 text-sm font-bold"></textarea>
                <button class="h-12 w-full rounded-2xl bg-[#2f6bff] text-sm font-extrabold text-white">Ajouter</button>
            </div>
        </form>
        <section class="rounded-[28px] bg-white p-5 shadow-xl shadow-[#173e7a]/8 ring-1 ring-[#dce6f7]">
            <div class="overflow-x-auto rounded-2xl border border-[#edf2fb]"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-[#f7faff] text-xs font-extrabold uppercase text-[#7d8aa7]"><tr><th class="px-4 py-3">Forfait</th><th class="px-4 py-3">Prix</th><th class="px-4 py-3">Limite</th><th class="px-4 py-3">Commission</th><th class="px-4 py-3">Statut</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-[#edf2fb]">@forelse($plans as $plan)<tr><td class="px-4 py-4 font-extrabold text-[#07152f]">{{ $plan->name }}</td><td class="px-4 py-4 font-extrabold">{{ number_format($plan->price, 0, ',', ' ') }} {{ $plan->currency }} / {{ $plan->billing_period }}</td><td class="px-4 py-4 font-bold text-[#64708a]">{{ $plan->active_venues_limit ?? 'Illimité' }}</td><td class="px-4 py-4 font-bold text-[#64708a]">{{ $plan->reduced_commission_rate ?? 'Standard' }}{{ $plan->reduced_commission_rate ? '%' : '' }}</td><td class="px-4 py-4">{{ $plan->is_active ? 'Actif' : 'Inactif' }}</td><td class="px-4 py-4 text-right"><x-dashboards.action-menu><form method="POST" action="{{ route('sap.subscription-plans.toggle', $plan) }}">@csrf<button class="w-full rounded-xl px-3 py-2 text-left {{ $plan->is_active ? 'text-[#b42318] hover:bg-[#fff6f6]' : 'text-[#2f6bff] hover:bg-[#f2f7ff]' }}">{{ $plan->is_active ? 'Désactiver ce forfait' : 'Réactiver ce forfait' }}</button></form></x-dashboards.action-menu></td></tr>@empty<tr><td colspan="6" class="px-4 py-10 text-center font-semibold text-[#64708a]">Aucun forfait.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $plans->links() }}</div>
        </section>
    </div>
</x-dashboards.sap-shell>
